#!/bin/bash

if [ "$ILABS_L0ShowOnRequestLogging" == "YES" ]; then
	set -avx
fi

function L0AddLocalDepsIncludeIfNeededInDirectory()
{	
	LOCAL_FILE="$1"/Local.xcconfig
	
	if [ -f "$LOCAL_FILE" ]; then
		grep -q "#include \"Dependencies.xcconfig\"" "$LOCAL_FILE"
		if [ "$?" == 1 ]; then
			echo "#include \"Dependencies.xcconfig\"" >> "$LOCAL_FILE"
		fi
	else
		echo "#include \"Dependencies.xcconfig\"" >> "$LOCAL_FILE"
	fi
}

if [ "$ILABS_DoNotUpdateSubmodules" != "YES" ]; then
	git submodule init
	git submodule update
fi

# MuiKit needs to point to Tools.

L0AddLocalDepsIncludeIfNeededInDirectory MuiKit
cat > MuiKit/Dependencies.xcconfig << EOF
INFINITELABS_TOOLS = \$(SRCROOT)/../Tools
EOF

# Mover needs to point to MuiKit and Tools

L0AddLocalDepsIncludeIfNeededInDirectory Mover
touch Mover/Local-Debug.xcconfig
touch Mover/Local-Release.xcconfig
cat > Mover/Dependencies.xcconfig << EOF
INFINITELABS_TOOLS = \$(SRCROOT)/../Tools
INFINITELABS_LIB_MUIKIT = \$(SRCROOT)/../MuiKit
EOF

L0AddLocalDepsIncludeIfNeededInDirectory Mover/3/iPhone
touch Mover/3/iPhone/Local-Debug.xcconfig
touch Mover/3/iPhone/Local-Release.xcconfig
cat > Mover/3/iPhone/Dependencies.xcconfig << EOF
INFINITELABS_TOOLS = \$(SRCROOT)/../../../Tools
INFINITELABS_LIB_MUIKIT = \$(SRCROOT)/../../../MuiKit
EOF

L0AddLocalDepsIncludeIfNeededInDirectory Mover/3/Network+Storage
touch Mover/3/Network+Storage/Local-Debug.xcconfig
touch Mover/3/Network+Storage/Local-Release.xcconfig
cat > Mover/3/Network+Storage/Dependencies.xcconfig << EOF
INFINITELABS_TOOLS = \$(SRCROOT)/../../../Tools
INFINITELABS_LIB_MUIKIT = \$(SRCROOT)/../../../MuiKit
EOF

# make sure SwapKit and other submodules, if any, are inited.
for i in Mover Tools MuiKit; do
	if [ -f "$i/.gitmodules" ]; then
		(cd "$i" && git submodule init && git submodule update) || exit 1
	fi
done

# Use the Variant script to set up the right variant.
if [ -x Mover/Scripts/Variants/Open ]; then
	Mover/Scripts/Variants/Open
elif [ -x Mover/Scripts/Variants/Plus ]; then
	Mover/Scripts/Variants/Plus
# Legacy variant setup
elif [ -x Mover/Scripts/Ads ]; then
	Mover/Scripts/Ads off
fi

if [ -x Mover/3/iPhone/Variants/Switch ]; then
	Mover/3/iPhone/Variants/Switch Open
fi

